---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(tidyNano)
library(themesoo)
```

```{r}
raw <- nanocombine(auto_name = TRUE) %>% 
  rename_all(str_replace_all, pattern = 'NA', replacement = 'None')

raw
```

```{r}
tidy_df <- raw %>%
  nanotidy(sep_var = c("Condition","GD","Exo_type","Tech_rep","NA1","NA2","NA3","NA4","Dilution")) %>% 
  select(-(NA1:NA4))
  
tidy_df
```

```{r}
tidy_df %>% 
  ggplot(aes(particle_size,True_count, color = Tech_rep)) +
  geom_line(size = 1) +
  facet_wrap(GD ~ Condition) +
  theme_soo()
```
```{r}
tidy_mean_df <- tidy_df %>% 
  nanolyze(particle_size, Condition, GD, Exo_type, name = "Tech_rep",param_var = True_count)


tidy_mean_df
```

```{r}
tidy_mean_df %>% 
  ggplot(aes(particle_size,Tech_rep_mean,color = Condition)) +
  geom_line(size = 1) +
  facet_wrap(~Exo_type) +
  theme_soo()

```
```{r}
count_df <- tidy_df %>% 
  nanocount(Condition, GD,Exo_type, Tech_rep, param_var = True_count) %>% 
  nanolyze(Condition, GD, Exo_type, param_var = Particle_count) %>% 
  select(-Param_sd,-Param_se)


count_df %>% 
  mutate(particles_per_ul = Param_mean/1000,
         particles_E8format_ul = particles_per_ul/1E8,
         totalpart_billons = particles_per_ul *100/1E9,
         amount_needed_for20billion = 20/totalpart_billons*100)



```

