---
title: "R Notebook"
output: html_notebook
---

# Objective
To determine the concentration of exosomes in plasma and placental explant culture samples.


```{r}
library(tidyverse)
library(tidyNano)
library(themesoo)
```



```{r}
df <- nanocombine()

df
```

```{r}
tidy_df <- df %>%
  nanotidy(sep_var = c("Source","GD", "Dilution", "Tech_rep"))

tidy_df

```
```{r}
tidy_df %>%
  ggplot(aes(particle_size, True_count, color = Tech_rep )) +
  geom_line(size = 1) +
  facet_wrap(~GD)
```


```{r}
mean_df <- tidy_df %>% 
  nanolyze(particle_size,Source, GD,
          param_var = True_count) %>% 
  unite(col = Sample, c("Source", "GD"), sep = "_")


mean_df
```

```{r}
mean_df %>% 
  ggplot(aes(particle_size, Param_mean, color = Sample)) +
  geom_line(size = 1)
```
```{r}
tidy_df %>% 
  nanocount(Source, GD, Tech_rep, param_var = True_count) %>% 
  ungroup() %>% 
  nanolyze(Source, GD, param_var = Particle_count) %>% 
  mutate( Sci_part_count = formatC(Param_mean/1000, format = "e", digits = 2),
    half = formatC(Param_mean/2, format = "e", digits = 2))
```

