---
title: "R Notebook"
output: html_notebook
---
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(tidyNano)
library(themesoo)

# devtools::install_github("soohyuna/themesoo")

```



```{r}

df01_raw <- nanoimport("2019-08-26_Pexo_plasma_qEV_conc-ExperimentSummary.csv") %>% 
  nanotidy(sep = c("Status", "Source","Dilution", "Tech_rep"))

df01_raw
```

```{r}
df01_raw %>% 
  filter(particle_size < 500) %>% 
  ggplot(aes(particle_size, True_count, color = Tech_rep)) +
  geom_line(size = 1) +
  facet_wrap(Source~Status)
```

```{r}
df01_raw %>% 
  nanocount(Status, Source, Tech_rep, param_var = True_count) %>% 
  ggplot(aes(Source,Particle_count,  color = Status)) +
  geom_jitter(width = 0.05) +
  facet_wrap(~Status)
```


```{r}
df02_count <- df01_raw %>% 
  nanocount(Status, Source, Tech_rep, param_var = True_count) %>% 
  nanolyze(Status, Source, param_var = Particle_count)
 
df02_count
```

```{r}
df02_count %>% 
  mutate(Mean_conc_per_ul = Param_mean/1000,
         Total_amount = Mean_conc_per_ul * 100)
```

